Cleanup e2e test inputs

diff --git a/scripts/run-e2e-tests b/scripts/run-e2e-tests
--- a/scripts/run-e2e-tests
+++ b/scripts/run-e2e-tests
@@ -8,6 +8,8 @@ find "${REPO_PATH}/e2e_test_inputs" -name __pycache__ -exec rm -rf {} \+
 cd "$REPO_PATH" || exit 1
 
 for project in ./e2e_test_inputs/*; do
+    project=${project#./}
+
     echo "===== Test $project ====="
     if [ -f "$REPO_PATH/$project/skip_main" ]; then
         echo "Skip testing main due to:"
@@ -18,13 +20,24 @@ for project in ./e2e_test_inputs/*; do
     fi
 
     echo "Test cycles..."
+    if [ -f "$REPO_PATH/$project/packages" ]; then
+        packages=""
+        while read -r line; do
+            for word in $line; do
+                packages="$packages $REPO_PATH/$project/$word"
+            done
+        done <"$REPO_PATH/$project"/packages
+    else
+        packages="$REPO_PATH/$project/pkg"
+    fi
 
-    threshold="$(cat "$REPO_PATH/$project"/found_cycles)"
-    result=$(PYTHONPATH="." ./run-main --packages "$REPO_PATH/$project" --strategy johnson 2>&1)
-    if [ "$result" == "Found $threshold import cycles" ]; then
+    num_cycles="$(cat "$REPO_PATH/$project"/found_cycles)"
+    # shellcheck disable=SC2086
+    result=$(PYTHONPATH="." ./run-main --packages $packages --strategy johnson 2>&1)
+    if [ "$result" == "Found $num_cycles import cycles" ]; then
        continue
     fi
-    echo "Test $project failed (expect $threshold cycles, got '$result')." >&2
+    echo "Test $project failed (expect $num_cycles cycles, got '$result')." >&2
     exit 1
 done
 
