Add opt '--threshold'

diff --git a/scripts/run-e2e-tests b/scripts/run-e2e-tests
--- a/scripts/run-e2e-tests
+++ b/scripts/run-e2e-tests
@@ -20,9 +20,10 @@ for project in ./e2e_test_inputs/*; do
 
     echo "Test cycles..."
 
-    output=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/$project" 2>&1)
-    if ! echo "$output" | grep -q "Found $(cat "$REPO_PATH/$project"/found_cycles) import cycles"; then
-        echo "Test $project failed (number of cycles)." >&2
+    threshold="$(cat "$REPO_PATH/$project"/found_cycles)"
+    PYTHONPATH="." ./run-main --project-path "$REPO_PATH/$project" --threshold "$threshold" >/dev/null 2>&1
+    if ! echo $? >/dev/null; then
+        echo "Test $project failed (number of cycles exceeds $threshold)." >&2
         exit 1
     fi
 done
@@ -30,8 +31,8 @@ done
 echo "===== Self test ====="
 echo "Test cycles..."
 
-self_output=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/py_import_cycles" 2>&1)
-if ! echo "$self_output" | grep -q "Found 0 import cycles"; then
-    echo "Self test failed: $output." >&2
+PYTHONPATH="." ./run-main --project-path "$REPO_PATH/py_import_cycles" >/dev/null 2>&1
+if ! echo $? >/dev/null; then
+    echo "Self test failed: Found cycles." >&2
     exit 1
 fi
