Make e2e tests more robust

diff --git a/scripts/run-e2e-tests b/scripts/run-e2e-tests
--- a/scripts/run-e2e-tests
+++ b/scripts/run-e2e-tests
@@ -20,8 +20,8 @@ for project in ./e2e_test_inputs/*; do
 
     echo "Test cycles..."
 
-    last_line=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/$project" 2>&1 | tail -n1)
-    if ! echo "$last_line" | grep -q "Found $(cat "$REPO_PATH/$project"/found_cycles) import cycles"; then
+    output=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/$project" 2>&1)
+    if ! echo "$output" | grep -q "Found $(cat "$REPO_PATH/$project"/found_cycles) import cycles"; then
         echo "Test $project failed (number of cycles)." >&2
         exit 1
     fi
@@ -30,8 +30,8 @@ done
 echo "===== Self test ====="
 echo "Test cycles..."
 
-self_last_line=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/py_import_cycles" 2>&1 | tail -n1)
-if ! echo "$self_last_line" | grep -q "Found 0 import cycles"; then
-    echo "Self test failed: $self_last_line." >&2
+self_output=$(PYTHONPATH="." ./run-main --project-path "$REPO_PATH/py_import_cycles" 2>&1)
+if ! echo "$self_output" | grep -q "Found 0 import cycles"; then
+    echo "Self test failed: $output." >&2
     exit 1
 fi
